# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
  - vendor/

services:
    - redis:latest

test:7:
    before_script:
      - bash build/docker_install.sh > /dev/null
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar update
      - php composer.phar install
    image: php:7
    script:
      - vendor/bin/phpunit --coverage-text --colors=never
      
test:7.1:
    before_script:
      - bash build/docker_install.sh > /dev/null
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar update
      - php composer.phar install
    image: php:7.1
    script:
      - vendor/bin/phpunit --coverage-text --colors=never
