# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
  - vendor/

test:7:
    before_script:
      - sh build/docker_install.sh > /dev/null
      - apk add --no-cache php7-phpdbg
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar update
      - php composer.phar install
    image: php:7-alpine
    script:
      - phpdbg -qrr -- vendor/bin/phpunit --coverage-text --colors=never
      
test:7.1:
    before_script:
      - sh build/docker_install.sh > /dev/null
      - apk add --no-cache php7.1-phpdbg
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar update
      - php composer.phar install
    image: php:7.1-alpine
    script:
      - phpdbg -qrr -- vendor/bin/phpunit --coverage-text --colors=never
