language: php

install:
  - composer install

php:
  - 7.1
  - 7.2
  - nightly

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c build

services:
  - redis

matrix:
  allow_failures:
    - php: nightly