language: php

install:
  - composer install

php:
  - 5.6
  - 7
  - hhvm
  - nightly

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c build

services:
  - redis

matrix:
  allow_failures:
    - php: nightly